###############################################################################
#                          Zavarka Team Support                               #
###############################################################################
services:
    memcached:
      image: memcached:alpine
      container_name: atlantm-api-memcached
      ports:
        - "11211:11211"
    ftp:
      image: delfer/alpine-ftp-server
      container_name: atlantm-api-ftp
      restart: always
      volumes:
        - ./vsftpd/vsftpd.conf:/etc/vsftpd/vsftpd.conf
        - ../ftp/:/ftp/
        - ${LOGS_DIR}/vsftpd:/var/log/
      ports:
        - "21:21"
        - "1024-1048:1024-1048"
      environment:
        USERS: ${FTP_USERS}
        ADDRESS: ${FTP_ADDRESS}
    sftp:
      image: emberstack/sftp
      container_name: atlantm-api-sftp
      volumes:
        - /srv/ftp/XXXX:/home/XXXX/upload
        - ./sftp/sftp-config.json:/app/config/sftp.json:ro
      ports:
        - "22122:22"
    nginx:
      image: nginx:alpine
      container_name: atlantm-api-nginx
      working_dir: ${WORKING_DIR}
      restart: always
      volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
        - ./nginx/default.d:/etc/nginx/default.d:ro
        - ./nginx/params:/etc/nginx/params:ro
        - ./nginx/vhost:/etc/nginx/vhost:ro
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro
        - ./nginx/htpasswd:/etc/nginx/htpasswd:ro
        - ../www:${WORKING_DIR}
        - ${LOGS_DIR}/nginx:/var/log/nginx
        - ${LOGS_DIR}/nginx/default:/var/www/default/logs
        - ${LOGS_DIR}/nginx/xxx.com:/var/www/xxx.com/logs
        # - ${LOGS_DIR}/nginx/blog.xxx.com:/var/www/blog.xxx.com/logs
      ports:
       - 80:80
       - 10080:10080
      links:
        - php-fpm74
      depends_on:
        - php-fpm74
    php-fpm82:
      build: php-fpm8.2
      container_name: atlantm-api-php-fpm82
      working_dir: ${WORKING_DIR}
      volumes:
        - ../www:/srv/www
        - ../ftp/:/srv/ftp/
        # - ./php-fpm8.2/php-8.2.ini:/etc/php/8.2/fpm/php.ini
        - ./php-fpm8.2/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
        - ./php-fpm8.2/php-ini-overrides.ini:/etc/php/8.2/cli/conf.d/99-overrides.ini
        - ./php-fpm8.2/php-fpm.conf:/etc/php/8.2/fpm/php-fpm.conf
        - ./php-fpm8.2/pool.d:/etc/php/8.2/fpm/pool.d
        - ../docker/tmp/mysql:/var/lib/mysql/
        - ../docker/tmp/php:/tmp/
        - ${LOGS_DIR}/php/8.2/:/var/log/
        - ./.ssh/id_rsa:/home/ec2-user/.ssh/id_rsa
        - ~/.config/yandex-cloud:/var/www/.config/yandex-cloud
        - ~/yandex-cloud:/var/www/yandex-cloud
        - ~/.config/yandex-cloud:/root/.config/yandex-cloud
        - ~/yandex-cloud:/root/yandex-cloud
        - ./.aws/credentials:/root/.aws/credentials
      ports:
        - 9002:9002
      links:
        - db:db
      environment:
        PRODUCTION_TYPE: ${PRODUCTION_TYPE}
        APP_DEBUG: ${APP_DEBUG}
    php-fpm74:
      build: php-fpm7.4
      container_name: atlantm-api-php-fpm74
      working_dir: ${WORKING_DIR}
      volumes:
        - ../www:${WORKING_DIR}
        - ../ftp/:/srv/ftp/
        - ./php-fpm7.4/php-7.4.ini:/etc/php/7.4/fpm/php.ini
        - ./php-fpm7.4/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
        - ./php-fpm7.4/php-ini-overrides.ini:/etc/php/7.4/cli/conf.d/99-overrides.ini
        - ./php-fpm7.4/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
        - ./php-fpm7.4/pool.d:/etc/php/7.4/fpm/pool.d
        - ../docker/tmp/mysql:/var/lib/mysql/
        - ../docker/tmp/php:/tmp/
        - ${LOGS_DIR}/php/7.4/:/var/log/
        - ./.ssh/id_rsa:/home/ec2-user/.ssh/id_rsa
        - ~/.config/yandex-cloud:/var/www/.config/yandex-cloud
        - ~/yandex-cloud:/var/www/yandex-cloud
        - ~/.config/yandex-cloud:/root/.config/yandex-cloud
        - ~/yandex-cloud:/root/yandex-cloud
        - ./.aws/credentials:/root/.aws/credentials
      ports:
        - 9004:9004
      links:
        - db:db
      environment:
        PRODUCTION_TYPE: ${PRODUCTION_TYPE}
        APP_DEBUG: ${APP_DEBUG}
    db:
      image: mariadb:10.2
      container_name: atlantm-api-mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      working_dir: ${WORKING_DIR}
      volumes:
        - ../docker/mysql:/var/lib/mysql
        - ${LOGS_DIR}/mysql/:/var/log/mysql
        - ./mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        - ./mysql/mysql.conf.d/:/etc/mysql/mysql.conf.d
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    cloudbeaver: # db management
      image: dbeaver/cloudbeaver
      container_name: atlantm-api-cloudbeaver
      restart: always
      volumes:
        - ./cloudbeaver/cloudbeaver.conf:/workspace/.data/.cloudbeaver.runtime.conf
      ports:
        - 20080:8978
