###############################################################################
#                          Zavarka Team Support                               #
###############################################################################
version: "3.4"
x-common-variables:
  &common-variables
    PRODUCTION_TYPE: prod
    APP_DEBUG: 0
x-common-variables:
  &mysql-variables
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: atlantm
    MYSQL_USER: atlantm
    MYSQL_PASSWORD: AttriS#bute-Fridge-Hun@dredth7-Produc_t0-Almanac-Decipher
x-volumes:
  &project-volumes # {{папка локальная}}:{{папка на сервере}}
x-common-variables:
  &working-dir
    /srv/docker ## папка на сервере от корня
services:
    memcached:
      image: memcached:alpine
      container_name: atlantm-api-memcached

    # mysql:
    #   image: mysql:8.0
    #   container_name: atlantm-api-mysql
    #   working_dir: *working-dir
    #   volumes:
    #     - ../:/srv/amok/www/amok.shop/www
    #   environment:
    #     <<: *mysql-variables
    #   ports:
    #     - "10002:3306"

    webserver:
      image: nginx:alpine
      container_name: atlantm-api-nginx
      working_dir: *working-dir
      restart: always
      volumes:
        - /srv/www:/srv/docker
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
        - ./nginx/default.d:/etc/nginx/default.d:ro
        - ./nginx/params:/etc/nginx/params:ro
        - ./nginx/vhost:/etc/nginx/vhost:ro
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro
        - ./certbot/conf:/etc/nginx/certs:ro
        - /srv/docker/logs/nginx:/var/log/nginx
        - /srv/docker/logs/nginx:/var/www/html/default/logs
        - /srv/docker/logs/nginx:/var/www/html/xxx.com/logs
        - /srv/docker/logs/nginx:/var/www/html/blog.xxx.com/logs
      ports:
       - "80:80"
       - "443:443"
      links:
        - php-fpm
      depends_on:
        - php-fpm

    certbot:
      image: certbot/certbot:latest
      container_name: atlantm-api-certbot
      volumes:
        - ./certbot/www/:/var/www/certbot/:rw
        - ./certbot/conf/:/etc/letsencrypt/:rw
    php-fpm:
      build: php-fpm
      container_name: atlantm-api-php-fpm
      working_dir: *working-dir
      volumes:
        - /srv/www:/srv/docker
        - './php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        - './php-fpm/pool.d:/etc/php/8.1/fpm/pool.d'
        - '/srv/docker/logs/php/8.1/:/var/log/'
      ports:
       - 9000
      environment:
        <<: *common-variables
    #  #links:
    #  #  - "mysql:db"

    # composer:
    #   # image: composer/composer
    #   build: composer/1.8/
    #   ports:
    #     - "100003:9000"
    #   volumes:
    #     - ../www/:/composer
    #   container_name: atlantm-api-composer
    #   working_dir: /composer
    #   command: install

    # phpmyadmin:
    #   image: phpmyadmin/phpmyadmin
    #   container_name: phpmyadmin
    #   environment:
    #     - PMA_ARBITRARY=0
    #     - PMA_HOST=mysql
    #     - PMA_USER=root
    #     - PMA_PASSWORD=root
    #     - MYSQL_USER=pma
    #     - MYSQL_PASSWORD=pma
    #     - MYSQL_ROOT_PASSWORD=root
    #   volumes:
    #     - /sessions
    #     - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    #   depends_on:
    #     - mysql
    #   ports:
    #     - "10004:80"
#      command: cd sql;
#      links:
#        - "mysql:mysql"
