###############################################################################
#                          Zavarka Team Support                               #
###############################################################################
version: "3.4"
x-common-variables:
  &common-variables
    PRODUCTION_TYPE: prod
    APP_DEBUG: 0
x-common-variables:
  &ftp-variables
    USERS: "XXXX|XXXX|/ftp/new|10000 XXXX|XXXX|/ftp/trade-in|10002 XXXX|XXXX|/ftp/service-calc|10001"
    ADDRESS: "ftp.XXXX.ru"
x-common-variables:
  &mysql-variables
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: atlantm
    MYSQL_USER: atlantm
    MYSQL_PASSWORD: AttriS#bute-Fridge-Hun@dredth7-Produc_t0-Almanac-Decipher
x-volumes:
  &project-volumes # {{папка локальная}}:{{папка на сервере}}
x-common-variables:
  &working-dir
    /srv/docker ## папка на сервере от корня
services:
    memcached:
      image: memcached:alpine
      container_name: atlantm-api-memcached

    # mysql:
    #   image: mysql:8.0
    #   container_name: atlantm-api-mysql
    #   working_dir: *working-dir
    #   volumes:
    #     - ../:/srv/amok/www/amok.shop/www
    #   environment:
    #     <<: *mysql-variables
    #   ports:
    #     - "10002:3306"
    ftp:
      image: delfer/alpine-ftp-server
      container_name: atlantm-api-ftp
      volumes:
        - ./vsftpd/vsftpd.conf:/etc/vsftpd/vsftpd.conf
        - ../ftp/:/ftp/
        - /srv/docker/logs/vsftpd:/var/log/
      ports:
        - "21:21"
        - "21000-21010:21000-21010"
      environment:
        <<: *ftp-variables
    webserver:
      image: nginx:alpine
      container_name: atlantm-api-nginx
      working_dir: /srv/www
      restart: always
      volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
        - ./nginx/default.d:/etc/nginx/default.d:ro
        - ./nginx/params:/etc/nginx/params:ro
        - ./nginx/vhost:/etc/nginx/vhost:ro
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro
        - ./certbot/conf:/etc/nginx/certs:ro
        - /srv/www:/srv/www
        - /srv/docker/logs/nginx:/var/log/nginx
        - /srv/docker/logs/nginx/default:/var/www/default/logs
        - /srv/docker/logs/nginx/xxx.com:/var/www/xxx.com/logs
        - /srv/docker/logs/nginx/blog.xxx.com:/var/www/blog.xxx.com/logs
      ports:
       - "80:80"
       - "443:443"
       - "10080:10080"
      links:
        - php-fpm
      depends_on:
        - php-fpm

    certbot:
      image: certbot/certbot:latest
      container_name: atlantm-api-certbot
      volumes:
        - ./certbot/www/:/var/www/certbot/:rw
        - ./certbot/conf/:/etc/letsencrypt/:rw
    php-fpm:
      build: php-fpm
      container_name: atlantm-api-php-fpm
      working_dir: /srv/www
      volumes:
        - '/srv/www:/srv/www'
        - './php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        - './php-fpm/pool.d:/etc/php/8.1/fpm/pool.d'
        - '/srv/docker/logs/php/8.1/:/var/log/'
      ports:
       - "9000:9000"
      environment:
        <<: *common-variables
      # links:
      #   - "mysql:db"

    # composer:
    #   build: composer/1.8/
    #   container_name: atlantm-api-composer
    #   working_dir: /composer
    #   volumes:
    #     - /srv/www/:/composer
    #   ports:
    #     - "100003:9000"
    #   command: install

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        - PMA_ARBITRARY=0
        - PMA_HOST=rc1b-6hjqm8by6fiennpe.mdb.yandexcloud.net
        - PMA_PORT=3306
        - PMA_USER=myadmin
        - PMA_PASSWORD=Vagra#ncy6MooSnlightUtmost
        - MYSQL_USER=myadmin
        - MYSQL_PASSWORD=Vagra#ncy6MooSnlightUtmost
      volumes:
        - /sessions
        - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        - /srv/docker/logs/phpmyadmin:/var/log
        - ./mysql/crt:/mysql
      ports:
        - "10004:80"
      depends_on:
        - mysql
      # command: cd sql;
      # links:
      #   - "mysql:mysql"
