###############################################################################
#                          Zavarka Team Support                               #
###############################################################################
version: "3.4"
x-common-variables:
  &common-variables
    PRODUCTION_TYPE: prod
    APP_DEBUG: 0
x-common-variables:
  &ftp-variables
    USERS: "XXXX|XXXX|/ftp/new|10000 XXXX|XXXX|/ftp/trade-in|10002 XXXX|XXXX|/ftp/service-calc|10001"
    ADDRESS: "ftp.XXXX.ru"
x-volumes:
  &project-volumes # {{папка локальная}}:{{папка на сервере}}
x-common-variables:
  &working-dir
    /srv/docker ## папка на сервере от корня
services:
    memcached:
      image: memcached:alpine
      container_name: atlantm-api-memcached
      ports:
        - "11211:11211"
    ftp:
      image: delfer/alpine-ftp-server
      container_name: atlantm-api-ftp
      restart: always
      volumes:
        - ./vsftpd/vsftpd.conf:/etc/vsftpd/vsftpd.conf
        - ../ftp/:/ftp/
        - ../docker/logs/vsftpd:/var/log/
      ports:
        - "21:21"
        - "1024-1048:1024-1048"
      environment:
        <<: *ftp-variables
    webserver:
      image: nginx:alpine
      container_name: atlantm-api-nginx
      working_dir: /srv/www
      restart: always
      volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
        - ./nginx/default.d:/etc/nginx/default.d:ro
        - ./nginx/params:/etc/nginx/params:ro
        - ./nginx/vhost:/etc/nginx/vhost:ro
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro
        - ./nginx/htpasswd:/etc/nginx/htpasswd:ro
        # - ./certbot/conf:/etc/nginx/certs:ro
        - ../www:/srv/www
        - ../docker/logs/nginx:/var/log/nginx
        - ../docker/logs/nginx/default:/var/www/default/logs
        - ../docker/logs/nginx/xxx.com:/var/www/xxx.com/logs
        # - /srv/docker/logs/nginx/blog.xxx.com:/var/www/blog.xxx.com/logs
      ports:
       - "80:80"
       - "10080:10080"
      links:
        - php-fpm73
      depends_on:
        - php-fpm73
    php-fpm73:
      build: php-fpm7.3
      container_name: atlantm-api-php-fpm73
      working_dir: /srv/www
      volumes:
        - '../www:/srv/www'
        - '../ftp/:/srv/ftp/'
        - './php-fpm7.3/php-7.3.ini:/etc/php/7.3/fpm/php.ini'
        - './php-fpm7.3/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini'
        - './php-fpm7.3/php-ini-overrides.ini:/etc/php/7.3/cli/conf.d/99-overrides.ini'
        - './php-fpm7.3/php-fpm.conf:/etc/php/7.3/fpm/php-fpm.conf'
        - './php-fpm7.3/pool.d:/etc/php/7.3/fpm/pool.d'
        - '../docker/tmp/mysql:/var/lib/mysql/'
        - '../docker/tmp/php:/tmp/'
        - '../docker/logs/php/7.3/:/var/log/'
        - './php-fpm7.3/ImageMagick-6/policy.xml:/etc/ImageMagick-6/policy.xml'
        # - '/srv/docker/logs/cron:/var/log/cron'
        - './.ssh/id_rsa:/home/ec2-user/.ssh/id_rsa'
        - '~/.config/yandex-cloud:/var/www/.config/yandex-cloud'
        - '~/yandex-cloud:/var/www/yandex-cloud'
        - '~/.config/yandex-cloud:/root/.config/yandex-cloud'
        - '~/yandex-cloud:/root/yandex-cloud'
        - './.aws/credentials:/root/.aws/credentials'
      ports:
       - "9003:9003"
      links:
        - db:db
      environment:
        <<: *common-variables
    db:
      image: mariadb:10.2
      container_name: atlantm-api-mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      working_dir: /srv/www
      volumes:
        - '../docker/mysql:/var/lib/mysql'
        - './mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf'
        - './mysql/mysql.conf.d/:/etc/mysql/mysql.conf.d'
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: 'XXXX'
        MYSQL_DATABASE: 'atlantm'
        MYSQL_USER: 'atlantm'
        MYSQL_PASSWORD: 'XXXX'
    
    # adminer:
    #   image: adminer
    #   container_name: atlantm-api-adminer
    #   ports:
    #     - 20080:8080
    apidoc:
      build: apidoc
      container_name: atlantm-api-apidoc

    # php-fpm:
    #   build: php-fpm
    #   container_name: atlantm-api-php-fpm
    #   working_dir: /srv/www
    #   volumes:
    #     - '/srv/www:/srv/www'
    #     - './php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
    #     - './php-fpm/php-fpm.conf:/etc/php/8.1/fpm/php-fpm.conf'
    #     - './php-fpm/pool.d:/etc/php/8.1/fpm/pool.d'
    #     - '/srv/docker/logs/php/8.1/:/var/log/'
    #   ports:
    #    - "9000:9000"
    #   environment:
    #     <<: *common-variables
    # php-fpm74:
    #   build: php-fpm7.4
    #   container_name: atlantm-api-php-fpm74
    #   working_dir: /srv/www
    #   volumes:
    #     - '/srv/www:/srv/www'
    #     - './php-fpm7.4/php-7.4.ini:/etc/php/7.4/fpm/php.ini'
    #     - './php-fpm7.4/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
    #     - './php-fpm7.4/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf'
    #     - './php-fpm7.4/pool.d:/etc/php/7.4/fpm/pool.d'
    #     - '/srv/docker/logs/php/7.4/:/var/log/'
    #   ports:
    #    - "9004:9004"
    #   environment:
    #     <<: *common-variables

    # certbot:
    #   image: certbot/certbot:latest
    #   container_name: atlantm-api-certbot
    #   volumes:
    #     - ./certbot/www/:/var/www/certbot/:rw
    #     - ./certbot/conf/:/etc/letsencrypt/:rw

    # composer:
    #   build: composer/1.8/
    #   container_name: atlantm-api-composer
    #   working_dir: /composer
    #   volumes:
    #     - /srv/www/:/composer
    #   ports:
    #     - "100003:9000"
    #   command: install

    # phpmyadmin:
    #   image: phpmyadmin/phpmyadmin
    #   container_name: atlantm-api-phpmyadmin
    #   environment:
    #     - PMA_ARBITRARY=1
    #     - PMA_HOST=rc1b-6hjqm8by6fiennpe.mdb.yandexcloud.net
    #     - PMA_PORT=3306
    #     - PMA_USER=myadmin
    #     - PMA_PASSWORD=Vagra#ncy6MooSnlightUtmost
    #   volumes:
    #     - /sessions
    #     - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    #     - /srv/docker/logs/phpmyadmin:/var/log
    #     - ./mysql/crt:/var/www/html/mysql
    #   ports:
    #     - "10004:80"
    #   # depends_on:
    #   #   - mysql
    #   # command: cd sql;
    #   # links:
    #   #   - "mysql:mysql"
